server:
  port: 9001
  servlet:
    context-path: /shop/api/v1

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mobile_phone_sale?serverTimezone=UTC
    username: root
    password: 123456
    driver-class-name: org.mariadb.jdbc.Driver

mybatis-plus:
  type-aliases-package: com.phoneshop.shop.entity
  global-config:
    db-config:
      id-type: auto

  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl


